# Generated by Django 3.2 on 2021-05-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
