# Generated by Django 3.2 on 2021-05-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0002_auto_20210513_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='colour',
        ),
    ]
