# Generated by Django 3.2 on 2021-05-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0003_remove_furniture_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='colour',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
