# Generated by Django 3.2 on 2021-06-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0004_furniture_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='model_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='pid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='comments',
            name='uid',
            field=models.CharField(max_length=10),
        ),
    ]
