# Generated by Django 3.2 on 2021-05-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles', '0002_auto_20210530_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
