# Generated by Django 3.2 on 2021-05-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles', '0003_auto_20210513_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='pid',
            field=models.CharField(max_length=10),
        ),
    ]
