# Generated by Django 3.2 on 2021-05-30 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles', '0004_auto_20210530_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='star1',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='star2',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='star3',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='star4',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='star5',
        ),
    ]
