# Generated by Django 3.2 on 2021-05-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles', '0004_alter_comments_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uid',
            field=models.CharField(max_length=10),
        ),
    ]
