# Generated by Django 3.2 on 2021-05-23 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mobiles', '0005_alter_comments_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mobiles.mobiles', to_field='product_id'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles_uid', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
