# Generated by Django 3.2 on 2021-05-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobiles', '0006_auto_20210523_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='pid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='comments',
            name='uid',
            field=models.CharField(max_length=10),
        ),
    ]
