# Generated by Django 3.2 on 2021-06-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('uid', models.CharField(max_length=10)),
                ('rating', models.FloatField(default=0)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
