# Generated by Django 3.2 on 2021-06-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clothing', '0001_initial'),
    ]

    operations = [
    ]
